use strict;
use warnings;
use Switch;

#automata for log file processing..

# expects as input a file ($fname.4rows) generated by grep -E "^Real|^maximum resident|^VERIFICATION \./|VERIFICATION SUCC|VERIFICATION FAIL" <log_file> >  $fname.4rows

#
my $count=0;
my @RealTime = ();
my $bugTO = 0;
my @maxRSS = ();
my @fname = ();
my $line = "";
my $decided = 0;

while(<>){
  chomp;
  $line = $_;
       #print "$count";
  switch ($count) {
    case 0 
      { #print ">$count";
        if ($line eq "VERIFICATION SUCCESSFUL"){
          printf "%- 5s ", "UNSAT";
          $decided = 1;
        }elsif ($line eq "VERIFICATION FAILED"){
          printf "%- 5s ", "SAT";
          $decided = 1;
        }elsif ($line =~ /^Real time/){
            @RealTime = split ' ', $line;
            $bugTO = 1;
            if($RealTime[3] >= 900){
              printf "%- 5s ", "TO"
            }else{
              printf "%- 5s ", "BUG"
            }
            printf "%-8.3f ", $RealTime[3];
        }else{
          die("Neither outcome, nor RealTime!! (count =$count): $line...");
        }
        $count=1;
      }

    case 1 
      { 
       #print ">$count";
        if ($bugTO){ #need to check if it is maxrss.
          @maxRSS = split ' ', $line;
          printf "%-11.3f ", $maxRSS[4]/1024;
          $count=3;
        }elsif ($line =~ /^Real time/){
          @RealTime = split ' ', $line;
          $bugTO = 1;
          if($RealTime[3] >= 900){
            (!$decided) && do {printf "%- 5s ", "TO"}
          }else{
            (!$decided) && do {printf "%- 5s ", "BUG"}
          }
          printf "%-8.3f ", $RealTime[3];
          $count=2;
        }else{
          die("Neither RealTime, nor maxRSS!! (count =$count): $line\n");
      }
    }

  case 2 
    {
       #print ">$count";
      if (!$bugTO){
        @fname = split ' ', $line;
        printf "%-s\n", $fname[1];
        $count=0;
        @RealTime = ();
        $bugTO = 0;
        @maxRSS = ();
        @fname = ();
      }elsif($line =~ /^maximum/){
        @maxRSS = split ' ', $line;
        printf "%-11.3f ", $maxRSS[4]/1024;
        $count=3;
      }else{
      die("Neither maxRSS, nor fname!! (count =$count): $line\n");
      }
    }

  case 3 
    {
       #print ">$count";
      if($line =~ /^VERIFICATION .\//){
        @fname = split ' ', $line;
        printf "%-s\n", $fname[1]; 
      }else{
        die("No fname!! (count =$count): $line\n");
      }

      $count=0;
      @RealTime = ();
      $bugTO = 0;
      @maxRSS = ();
      @fname = ();
    }
  }
}
#end
